version: "2.2"
services:
  check-portal:
    container_name: patates
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - BUILD_TYPE=development
    ports:
      - '80:80'
    environment:
      - API_URL=https://patates.com/api/
